version: "3"
services:

  api:
    build: .
    volumes:
      - ".:/usr/src/app"
    command: "npm run dev"
    depends_on:
      - mongo
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development